
language: objective-c
osx_image: xcode8

before_install:
  - pod repo update

script:
  - swift -version
  - xcodebuild -version
  - xcodebuild -showsdks
  #- swiftlint
  - sleep 5
  - set -o pipefail
  - xcodebuild clean test -workspace ProjectRide.xcworkspace -scheme ProjectRide -destination "platform=iOS Simulator,name=iPhone 7 Plus"

