
language: objective-c
osx_image: xcode8

cache:
  - cocoapods # Caching Cocoa Pods to reduce build time

before_install:
  - pod repo update # need to do a repo update as the newest pods won't be available otherwise

script:
  - swift -version
  - xcodebuild -version
  - xcodebuild -showsdks
  #- swiftlint
  - sleep 5
  - set -o pipefail
  - xcodebuild clean test -workspace ProjectRide.xcworkspace -scheme ProjectRide -destination "platform=iOS Simulator,name=iPhone 7 Plus"

