language: objective-c
osx_image: xcode8

cache:
  - cocoapods # Caching Cocoa Pods to reduce build time

before_install:
  - pod repo update >/dev/null # need to do a repo update as the newest pods won't be available otherwise
  - gem install slather

script:
  - swiftlint lint --config .swiftlint.yml
  - sleep 5
  - xcodebuild clean test -workspace ProjectRide.xcworkspace -scheme ProjectRide -destination "platform=iOS Simulator,name=iPhone 7 Plus"

after_success:
  - slather

notifications:
  slack:
    rooms:
      - rideproject:cckd3V5cz51Mss8idF4qiU5j#general
      - rideproject:cckd3V5cz51Mss8idF4qiU5j#ios