
language: objective-c
osx_image: xcode8


script:
  - swift -version
  - xcodebuild -version
  - xcodebuild -showsdks
  #- swiftlint
  - sleep 5
  - set -o pipefail
  - xcodebuild clean test -project ProjectRide.xcodeproj -scheme ProjectRide -destination "platform=iOS Simulator,name=iPhone 7 Plus"

