language: objective-c

before_script:
- gem install cocoapods --verison 1.1.1
- pod repo update
 
script:
- xcodebuild build -scheme ProjectRide -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'

